//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agr_agreements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agr_agreements()
        {
            this.agr_processes = new HashSet<agr_processes>();
        }
    
        public int id_agreement { get; set; }
        public int id_agr_scheme { get; set; }
        public int id_agr_state { get; set; }
        public int id_agr_manager { get; set; }
        public int id_document { get; set; }
        public bool is_electron { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> id_creator { get; set; }
        public Nullable<int> old_id_agreement { get; set; }
    
        public virtual agr_documents agr_documents { get; set; }
        public virtual agr_schemes agr_schemes { get; set; }
        public virtual agr_states agr_states { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agr_processes> agr_processes { get; set; }
    }
}
