//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agr_proc_answers
    {
        public int id_proc_answer { get; set; }
        public int id_agr_process { get; set; }
        public string text { get; set; }
        public int id_creator { get; set; }
        public System.DateTime dattim1 { get; set; }
    }
}
