//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agr_matchers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agr_matchers()
        {
            this.agr_matchers2schemes = new HashSet<agr_matchers2schemes>();
        }
    
        public int id_agr_matcher { get; set; }
        public int id_user { get; set; }
        public string doc_type { get; set; }
        public string agr_type { get; set; }
        public string descr { get; set; }
        public Nullable<int> order_num { get; set; }
        public bool available { get; set; }
        public Nullable<int> id_main_matcher { get; set; }
        public bool enabled { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public Nullable<int> id_creator { get; set; }
        public Nullable<int> old_id_matcher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agr_matchers2schemes> agr_matchers2schemes { get; set; }
    }
}
