//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agr_states
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agr_states()
        {
            this.agr_agreements = new HashSet<agr_agreements>();
        }
    
        public int id_agr_state { get; set; }
        public string name { get; set; }
        public bool enabled { get; set; }
        public int order_num { get; set; }
        public string sys_name { get; set; }
        public Nullable<int> id_state_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agr_agreements> agr_agreements { get; set; }
    }
}
