//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agr_schemes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agr_schemes()
        {
            this.agr_agreements = new HashSet<agr_agreements>();
            this.agr_matchers2schemes = new HashSet<agr_matchers2schemes>();
        }
    
        public int id_agr_scheme { get; set; }
        public string name { get; set; }
        public bool enabled { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public int id_department { get; set; }
        public int id_contract_type { get; set; }
        public decimal amount1 { get; set; }
        public decimal amount2 { get; set; }
        public Nullable<int> old_id_agr_scheme { get; set; }
        public Nullable<int> id_creator { get; set; }
        public bool matchers_notice { get; set; }
        public Nullable<int> id_agr_scheme_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agr_agreements> agr_agreements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agr_matchers2schemes> agr_matchers2schemes { get; set; }
    }
}
