//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agr_doc_scan
    {
        public int id_doc_scan { get; set; }
        public int id_agreement { get; set; }
        public string name { get; set; }
        public string file_path { get; set; }
        public int id_creator { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> id_deleter { get; set; }
        public Nullable<int> id_parent { get; set; }
    }
}
