//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agr_processes
    {
        public int id_agr_process { get; set; }
        public int id_agreement { get; set; }
        public int id_agr_matcher { get; set; }
        public int order_num { get; set; }
        public Nullable<int> id_agr_result { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> date_change { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> id_updater { get; set; }
    
        public virtual agr_agreements agr_agreements { get; set; }
        public virtual agr_results agr_results { get; set; }
    }
}
