//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agr_documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agr_documents()
        {
            this.agr_agreements = new HashSet<agr_agreements>();
        }
    
        public int id_document { get; set; }
        public int id_doc_type { get; set; }
        public string number { get; set; }
        public string reg_number { get; set; }
        public Nullable<int> code_num { get; set; }
        public Nullable<System.DateTime> doc_date { get; set; }
        public string contract_num { get; set; }
        public Nullable<System.DateTime> contract_date { get; set; }
        public int id_department { get; set; }
        public int id_contract_type { get; set; }
        public Nullable<int> id_company { get; set; }
        public Nullable<int> id_contractor { get; set; }
        public decimal amount { get; set; }
        public Nullable<int> id_doc_manager { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> id_creator { get; set; }
        public Nullable<int> old_id_document { get; set; }
        public string add_docs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agr_agreements> agr_agreements { get; set; }
        public virtual agr_contract_types agr_contract_types { get; set; }
        public virtual agr_doc_types agr_doc_types { get; set; }
        public virtual departments departments { get; set; }
    }
}
