//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cities_load
    {
        public int id { get; set; }
        public string sla_1 { get; set; }
        public string sla_2 { get; set; }
        public string sla_3 { get; set; }
        public string sla_4 { get; set; }
        public string datetime_offset { get; set; }
    }
}
