//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cities
    {
        public int id_city { get; set; }
        public string name { get; set; }
        public bool enabled { get; set; }
        public int order_num { get; set; }
        public Nullable<int> id_creator { get; set; }
        public Nullable<System.DateTime> dattim1 { get; set; }
        public Nullable<System.DateTime> dattim2 { get; set; }
        public string region { get; set; }
        public string area { get; set; }
        public string locality { get; set; }
        public System.Data.Entity.Spatial.DbGeography coordinates { get; set; }
        public string coord { get; set; }
        public Nullable<int> sla_1 { get; set; }
        public Nullable<int> sla_2 { get; set; }
        public Nullable<int> sla_3 { get; set; }
        public Nullable<int> sla_4 { get; set; }
        public string datetime_offset { get; set; }
    }
}
