//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class counter
    {
        public int id_counter { get; set; }
        public int id_program { get; set; }
        public int id_user { get; set; }
        public System.DateTime date_came { get; set; }
        public string descr { get; set; }
        public string ip_address { get; set; }
        public string user_login { get; set; }
    }
}
