//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devinst_state_changes
    {
        public int id_state_change { get; set; }
        public int id_device_install { get; set; }
        public int id_devinst_state { get; set; }
        public Nullable<int> id_creator { get; set; }
        public System.DateTime date_change { get; set; }
        public bool enabled { get; set; }
        public bool notifed { get; set; }
    }
}
