//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devinst_device_installs
    {
        public int id_device_install { get; set; }
        public Nullable<int> id_claim { get; set; }
        public Nullable<int> id_contract { get; set; }
        public Nullable<int> id_contractor { get; set; }
        public string contractor { get; set; }
        public string et_number { get; set; }
        public string contract_number { get; set; }
        public Nullable<System.DateTime> plan_date { get; set; }
        public Nullable<int> id_device_model { get; set; }
        public Nullable<int> id_device { get; set; }
        public string device_model { get; set; }
        public string device { get; set; }
        public Nullable<int> id_city { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string object_name { get; set; }
        public string contact_name { get; set; }
        public string add_devices { get; set; }
        public Nullable<int> id_manager { get; set; }
        public Nullable<int> id_service_admin { get; set; }
        public string descr { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public Nullable<int> id_creator { get; set; }
        public bool enabled { get; set; }
        public int id_devinst_state { get; set; }
        public Nullable<int> old_id_device_install { get; set; }
    }
}
