//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_tab
    {
        public long id_log { get; set; }
        public int id_program { get; set; }
        public string proc_name { get; set; }
        public string @params { get; set; }
        public string descr { get; set; }
        public System.DateTime dattim { get; set; }
        public string user { get; set; }
        public int error_level { get; set; }
    }
}
