//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_agr_route
    {
        public string Подразделение { get; set; }
        public string Вид_договора { get; set; }
        public string Сумма_от { get; set; }
        public string Сумма_до { get; set; }
        public string ФИО_согл__лица { get; set; }
        public string Должность { get; set; }
        public int Порядковый_номер { get; set; }
    }
}
