//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public string Статус_согласования { get; set; }
        public string Тип_документа { get; set; }
        public string Вид_договора { get; set; }
        public string Подразделение { get; set; }
        public string Юр__лицо_Юнит { get; set; }
        public string Внешняя_организация { get; set; }
        public string ИНН_внешней_организации { get; set; }
        public decimal Сумма { get; set; }
        public string Менеджер { get; set; }
        public string Офис_менеджер { get; set; }
        public string Дата_начала_согласования__когда_создано_ { get; set; }
        public string Дата_окончания_согласования { get; set; }
        public Nullable<int> Продолжительность_согласования_в_рабочих_часах__с_момента_создания_ { get; set; }
    }
}
