//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class snmp_requests
    {
        public int id_requset { get; set; }
        public int id_exchange { get; set; }
        public Nullable<int> id_contractor { get; set; }
        public Nullable<int> id_device { get; set; }
        public string serial_num { get; set; }
        public string host { get; set; }
        public Nullable<int> counter { get; set; }
        public Nullable<int> counter_color { get; set; }
        public Nullable<System.DateTime> date_request { get; set; }
        public System.DateTime dattim1 { get; set; }
        public string prog_version { get; set; }
    }
}
