//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_akt_scans
    {
        public int id_akt_scan { get; set; }
        public string name { get; set; }
        public string file_name { get; set; }
        public string full_path { get; set; }
        public bool cames_add { get; set; }
        public Nullable<System.DateTime> date_cames_add { get; set; }
        public Nullable<int> id_adder { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> id_creator { get; set; }
    }
}
