//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_contract_devices
    {
        public string C__договора { get; set; }
        public string Контрагент { get; set; }
        public Nullable<System.DateTime> Дата_начала { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
        public string Тип_договора { get; set; }
        public string Менеджер { get; set; }
        public string Активен { get; set; }
        public string Город_полное { get; set; }
        public string Город { get; set; }
        public string Адрес { get; set; }
        public string Объект { get; set; }
        public string Периодичность_обслуживания { get; set; }
        public string Сервисный_администратор { get; set; }
        public string Модель { get; set; }
        public string Серийный_номер { get; set; }
        public string Классификатор { get; set; }
    }
}
