//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_device_data_view
    {
        public int id_device_data { get; set; }
        public int id_contract { get; set; }
        public int id_device { get; set; }
        public int counter { get; set; }
        public Nullable<int> counter_colour { get; set; }
        public Nullable<int> volume_counter { get; set; }
        public Nullable<int> volume_counter_colour { get; set; }
        public System.DateTime date_month { get; set; }
        public System.DateTime dattim1 { get; set; }
        public bool enabled { get; set; }
        public bool is_average { get; set; }
        public string number { get; set; }
        public string device { get; set; }
        public string contractor { get; set; }
    }
}
