//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_device_model_max_volume_load
    {
        public int id_device_model { get; set; }
        public Nullable<int> max_volume { get; set; }
        public bool loaded { get; set; }
        public Nullable<System.DateTime> date_load { get; set; }
    }
}
