//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_getEngeneerDayAlloc_curr_month
    {
        public Nullable<int> id_service_engeneer { get; set; }
        public System.DateTime date_came { get; set; }
        public Nullable<int> exec_claims { get; set; }
    }
}
