//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_active_device_coord_report
    {
        public string contract_number { get; set; }
        public string contractor { get; set; }
        public string device { get; set; }
        public string service_admin { get; set; }
        public string city { get; set; }
        public string object_name { get; set; }
        public string coordinates { get; set; }
        public string service_interval { get; set; }
        public string device_vendor { get; set; }
    }
}
