//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_device_model_with_classifier
    {
        public string Модель { get; set; }
        public string Категория { get; set; }
        public string Тип { get; set; }
        public string Подтип { get; set; }
        public string Вендор { get; set; }
        public string Рекоменд__нагр___нижн__порог_ { get; set; }
        public string Рекоменд__нагр___верхн__порог_ { get; set; }
        public Nullable<int> Макс__нагр_ { get; set; }
        public string Ресурс_аппарата { get; set; }
        public string Ед__изм__нагр_ { get; set; }
        public Nullable<int> Категория_трудоемкости { get; set; }
        public int ID_модели { get; set; }
        public string Код_подтипа { get; set; }
        public Nullable<int> РТО_t { get; set; }
        public Nullable<int> РЗРД_t { get; set; }
        public Nullable<int> МТС_t { get; set; }
        public Nullable<int> ЗНЗЧ_t { get; set; }
        public Nullable<int> ДНО_t { get; set; }
        public Nullable<int> МДО_t { get; set; }
        public Nullable<int> УРМ_t { get; set; }
        public Nullable<int> ИПТ_t { get; set; }
        public Nullable<int> ТЭО_t { get; set; }
        public Nullable<int> ЗРМ_t { get; set; }
        public Nullable<int> УТЗ_t { get; set; }
        public Nullable<int> НПР_t { get; set; }
        public Nullable<decimal> РТО_wi { get; set; }
        public Nullable<decimal> РЗРД_wi { get; set; }
        public Nullable<decimal> МТС_wi { get; set; }
        public Nullable<decimal> ЗНЗЧ_wi { get; set; }
        public Nullable<decimal> ДНО_wi { get; set; }
        public Nullable<decimal> МДО_wi { get; set; }
        public Nullable<decimal> УРМ_wi { get; set; }
        public Nullable<decimal> ИПТ_wi { get; set; }
        public Nullable<decimal> ТЭО_wi { get; set; }
        public Nullable<decimal> ЗРМ_wi { get; set; }
        public Nullable<decimal> УТЗ_wi { get; set; }
        public Nullable<decimal> НПР_wi { get; set; }
        public Nullable<decimal> РТО_f { get; set; }
        public Nullable<decimal> РЗРД_f { get; set; }
        public Nullable<decimal> МТС_f { get; set; }
        public Nullable<decimal> ЗНЗЧ_f { get; set; }
        public Nullable<decimal> ДНО_f { get; set; }
        public Nullable<decimal> МДО_f { get; set; }
        public Nullable<decimal> УРМ_f { get; set; }
        public Nullable<decimal> ИПТ_f { get; set; }
        public Nullable<decimal> ТЭО_f { get; set; }
        public Nullable<decimal> ЗРМ_f { get; set; }
        public Nullable<decimal> УТЗ_f { get; set; }
        public Nullable<decimal> НПР_f { get; set; }
        public Nullable<decimal> РТО_wc { get; set; }
        public Nullable<decimal> РЗРД_wc { get; set; }
        public Nullable<decimal> МТС_wc { get; set; }
        public Nullable<decimal> ЗНЗЧ_wc { get; set; }
        public Nullable<decimal> ДНО_wc { get; set; }
        public Nullable<decimal> МДО_wc { get; set; }
        public Nullable<decimal> УРМ_wc { get; set; }
        public Nullable<decimal> ИПТ_wc { get; set; }
        public Nullable<decimal> ТЭО_wc { get; set; }
        public Nullable<decimal> ЗРМ_wc { get; set; }
        public Nullable<decimal> УТЗ_wc { get; set; }
        public Nullable<decimal> НПР_wc { get; set; }
    }
}
