//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_plan_report
    {
        public string Модель { get; set; }
        public string Серийный_номер { get; set; }
        public string C__договора { get; set; }
        public Nullable<System.DateTime> Дата_начала_действия_договора { get; set; }
        public Nullable<System.DateTime> Дата_окончания_действия_договора { get; set; }
        public string Контрагент { get; set; }
        public string Адрес_места_расположения { get; set; }
        public string Менеджер { get; set; }
        public string Сервисный_администратор { get; set; }
        public string Интервал_обслуживания { get; set; }
        public string Месяц_обслуживания { get; set; }
        public string Статус { get; set; }
    }
}
