//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_device_list
    {
        public int id_device { get; set; }
        public string model { get; set; }
        public string serial_num { get; set; }
        public Nullable<decimal> speed { get; set; }
        public Nullable<int> counter { get; set; }
        public Nullable<int> age_count { get; set; }
        public Nullable<System.DateTime> instalation_date { get; set; }
        public string linked_now { get; set; }
        public string contract_num { get; set; }
        public Nullable<int> id_contract { get; set; }
        public Nullable<int> age { get; set; }
    }
}
