//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_cames_report
    {
        public string device { get; set; }
        public string serial_num { get; set; }
        public string number { get; set; }
        public string contractor_name { get; set; }
        public System.DateTime date_came { get; set; }
        public string engeneer { get; set; }
        public string admin { get; set; }
        public Nullable<int> counter { get; set; }
        public Nullable<int> counter_colour { get; set; }
        public string Классификатор { get; set; }
        public string Город { get; set; }
        public string Адрес { get; set; }
        public string Объект { get; set; }
        public string Город_полное { get; set; }
        public System.DateTime Дата_обслуживания { get; set; }
        public System.DateTime Дата_занесения_акта { get; set; }
        public string Тип_работ { get; set; }
    }
}
