//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_devices_no_plan
    {
        public string contractor_name { get; set; }
        public string contractor_inn { get; set; }
        public string number { get; set; }
        public string serial_num { get; set; }
        public string name { get; set; }
    }
}
