//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_contracts
    {
        public int id_contract { get; set; }
        public string number { get; set; }
        public Nullable<int> id_service_type { get; set; }
        public Nullable<int> id_contract_type { get; set; }
        public int id_contractor { get; set; }
        public int id_contract_status { get; set; }
        public Nullable<int> id_manager { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> date_begin { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public int id_creator { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> old_id_contract { get; set; }
        public Nullable<int> id_zip_state { get; set; }
        public string note { get; set; }
        public string contractor_name { get; set; }
        public string contractor_inn { get; set; }
        public Nullable<int> id_contract_prolong { get; set; }
        public Nullable<int> id_price_discount { get; set; }
        public Nullable<bool> period_reduction { get; set; }
        public bool add_plan_when_deactive { get; set; }
        public Nullable<int> handling_devices { get; set; }
        public Nullable<bool> client_sd_num_required { get; set; }
        public Nullable<System.TimeSpan> work_time_start { get; set; }
        public Nullable<System.TimeSpan> work_time_end { get; set; }
        public Nullable<bool> all_days { get; set; }
    }
}
