//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_getPlanExecuteDeviceList_curr_month
    {
        public string device { get; set; }
        public int id_device { get; set; }
        public Nullable<int> plan_cnt { get; set; }
        public Nullable<int> done_cnt { get; set; }
        public Nullable<int> residue { get; set; }
        public Nullable<decimal> done_percent { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string service_engeneer { get; set; }
        public Nullable<int> id_service_engeneer { get; set; }
        public Nullable<System.DateTime> date_came { get; set; }
        public int id_service_claim { get; set; }
        public int id_contractor { get; set; }
        public Nullable<int> id_service_admin { get; set; }
        public Nullable<int> id_manager { get; set; }
        public int id_contract { get; set; }
        public int is_limit_device_claims { get; set; }
    }
}
