//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_devices_no_graphik_load
    {
        public int id { get; set; }
        public string contractor { get; set; }
        public string number { get; set; }
        public Nullable<int> id_contract { get; set; }
        public Nullable<int> id_device { get; set; }
        public string serial_num { get; set; }
        public Nullable<int> id_service_interval { get; set; }
        public string service_interval { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public bool load { get; set; }
    }
}
