//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_tariff_features
    {
        public int id_feature { get; set; }
        public string sys_name { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public decimal price { get; set; }
        public bool enabled { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public int order_num { get; set; }
        public Nullable<int> id_creator { get; set; }
    }
}
