//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_payment_report
    {
        public int id_device { get; set; }
        public string device { get; set; }
        public Nullable<System.DateTime> planing_date { get; set; }
        public System.DateTime date_came { get; set; }
        public Nullable<decimal> payment { get; set; }
        public int id_service_engeneer { get; set; }
        public Nullable<decimal> tariff { get; set; }
        public string service_engeneer { get; set; }
    }
}
