//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_getEngeneerAllocList__curr_month
    {
        public Nullable<int> id_service_engeneer { get; set; }
        public string engeneer_city { get; set; }
        public string engeneer_org { get; set; }
        public string engeneer_pos { get; set; }
        public string service_engeneer { get; set; }
        public Nullable<int> cnt { get; set; }
        public Nullable<int> exec_claims { get; set; }
        public Nullable<int> days_in_month { get; set; }
        public Nullable<System.DateTime> last_claim_day { get; set; }
        public Nullable<System.DateTime> last_exec_day { get; set; }
        public Nullable<int> residue { get; set; }
        public Nullable<decimal> norm { get; set; }
        public int order_num { get; set; }
        public Nullable<int> exec_days { get; set; }
        public Nullable<decimal> cur_norm_exec { get; set; }
        public Nullable<decimal> cur_norm { get; set; }
        public Nullable<int> residue_days { get; set; }
        public Nullable<decimal> exec_diff { get; set; }
        public Nullable<decimal> norm_exec_percent { get; set; }
    }
}
