//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_devices_import
    {
        public int id { get; set; }
        public Nullable<int> id_model { get; set; }
        public string model_name { get; set; }
        public string serial_num { get; set; }
        public Nullable<System.DateTime> instal_date { get; set; }
        public Nullable<bool> adf { get; set; }
        public Nullable<bool> finisher { get; set; }
        public Nullable<bool> tray { get; set; }
        public System.DateTime dattim1 { get; set; }
        public bool import { get; set; }
        public Nullable<System.DateTime> date_import { get; set; }
        public Nullable<int> id_contract { get; set; }
        public Nullable<int> id_service_admin { get; set; }
        public Nullable<int> id_service_interval { get; set; }
        public Nullable<int> id_city { get; set; }
        public string address { get; set; }
        public string object_name { get; set; }
        public string contact_name { get; set; }
    }
}
