//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_devices_data_pivot
    {
        public string number { get; set; }
        public string device { get; set; }
        public string contractor { get; set; }
        public Nullable<int> id_contract { get; set; }
        public Nullable<int> id_device { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> counter { get; set; }
        public Nullable<int> counter_color { get; set; }
        public string place { get; set; }
        public string creator { get; set; }
        public System.DateTime date_create { get; set; }
    }
}
