//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_service_intervals
    {
        public int id_service_interval { get; set; }
        public string name { get; set; }
        public string nickname { get; set; }
        public string descr { get; set; }
        public int order_num { get; set; }
        public bool enabled { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public Nullable<int> id_service_interval_plan_group { get; set; }
        public Nullable<int> per_month { get; set; }
    
        public virtual srvpl_service_interval_plan_groups srvpl_service_interval_plan_groups { get; set; }
    }
}
