//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public srvpl_devices()
        {
            this.srvpl_service_zone2devices = new HashSet<srvpl_service_zone2devices>();
        }
    
        public int id_device { get; set; }
        public string serial_num { get; set; }
        public string inv_num { get; set; }
        public Nullable<int> counter { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> instalation_date { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public Nullable<int> id_creator { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> old_id_device { get; set; }
        public int id_device_model { get; set; }
        public Nullable<decimal> tariff { get; set; }
        public Nullable<int> counter_colour { get; set; }
        public string creator_sid { get; set; }
    
        public virtual srvpl_device_models srvpl_device_models { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<srvpl_service_zone2devices> srvpl_service_zone2devices { get; set; }
    }
}
