//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class srvpl_contract2devices
    {
        public int id_contract2devices { get; set; }
        public int id_contract { get; set; }
        public int id_device { get; set; }
        public int id_service_interval { get; set; }
        public int id_city { get; set; }
        public string address { get; set; }
        public string contact_name { get; set; }
        public string comment { get; set; }
        public Nullable<int> id_creator { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> id_service_admin { get; set; }
        public string object_name { get; set; }
        public System.Data.Entity.Spatial.DbGeography coordinates { get; set; }
        public string coord { get; set; }
        public Nullable<int> old_id_contract2devices { get; set; }
    }
}
