//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_device_counter_error
    {
        public int id_contract { get; set; }
        public int id_device { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> counter { get; set; }
        public Nullable<int> counter_color { get; set; }
        public string place { get; set; }
        public System.DateTime dattim1 { get; set; }
        public Nullable<int> prev_counter { get; set; }
        public Nullable<int> prev_counter_color { get; set; }
        public string prev_place { get; set; }
        public Nullable<System.DateTime> prev_date { get; set; }
    }
}
