//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id_user { get; set; }
        public string sid { get; set; }
        public string login { get; set; }
        public string full_name { get; set; }
        public string display_name { get; set; }
        public Nullable<int> id_position { get; set; }
        public Nullable<int> id_manager { get; set; }
        public Nullable<int> id_department { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string position { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string manager { get; set; }
        public string mail { get; set; }
        public string info { get; set; }
        public Nullable<int> id_city { get; set; }
        public string city { get; set; }
        public Nullable<int> id_company { get; set; }
        public string company { get; set; }
        public string department { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<int> id_state { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> old_id_user { get; set; }
    
        public virtual user_states user_states { get; set; }
    }
}
