//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zip_state_history_view
    {
        public int id { get; set; }
        public int id_claim { get; set; }
        public Nullable<System.DateTime> date_change { get; set; }
        public string name { get; set; }
        public string display_name { get; set; }
        public string department { get; set; }
    }
}
