//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zipcl_nomenclature_price
    {
        public int id_nomenclature { get; set; }
        public Nullable<int> load_num { get; set; }
        public string name { get; set; }
        public string catalog_num { get; set; }
        public string nomenclature_num { get; set; }
        public Nullable<decimal> price_rur { get; set; }
        public Nullable<decimal> price_usd { get; set; }
        public Nullable<decimal> price_eur { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public bool enabled { get; set; }
    }
}
