//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zipcl_numenclature_change
    {
        public string catalog_num { get; set; }
        public string nomenclature_num { get; set; }
        public System.DateTime dattim1 { get; set; }
        public bool load { get; set; }
    }
}
