//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zipcl_claim_unit_report
    {
        public int ID_Заявки { get; set; }
        public string C__ServiceDesk { get; set; }
        public string Дата_Заявки { get; set; }
        public string Каталожный_номер { get; set; }
        public string Номенклатурный_номер { get; set; }
        public string Наименование_ЗИП { get; set; }
        public string Модель_КМТ { get; set; }
        public string Серийный_номер { get; set; }
        public string Инженер { get; set; }
        public string Сервисный_администратор { get; set; }
        public string Менеджер { get; set; }
        public string Оператор { get; set; }
        public string Контрагент { get; set; }
    }
}
