//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zipcl_zip_claims
    {
        public int id_claim { get; set; }
        public Nullable<int> id_device { get; set; }
        public string serial_num { get; set; }
        public string device_model { get; set; }
        public string contractor { get; set; }
        public Nullable<int> id_contractor { get; set; }
        public string city { get; set; }
        public Nullable<int> id_city { get; set; }
        public string address { get; set; }
        public Nullable<int> counter { get; set; }
        public int id_engeneer_conclusion { get; set; }
        public int id_claim_state { get; set; }
        public string request_num { get; set; }
        public string descr { get; set; }
        public System.DateTime dattim1 { get; set; }
        public System.DateTime dattim2 { get; set; }
        public Nullable<int> id_engeneer { get; set; }
        public int id_creator { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> old_id_claim { get; set; }
        public Nullable<int> id_manager { get; set; }
        public Nullable<int> id_operator { get; set; }
        public Nullable<int> id_service_admin { get; set; }
        public string service_desk_num { get; set; }
        public Nullable<int> counter_colour { get; set; }
        public string cancel_comment { get; set; }
        public string object_name { get; set; }
        public string waybill_num { get; set; }
        public string et_state { get; set; }
        public string et_waybill_state { get; set; }
        public string contract_num { get; set; }
        public string contract_type { get; set; }
        public Nullable<int> id_et_way_claim_state { get; set; }
        public string contractor_sd_num { get; set; }
        public string et_plan_came_date { get; set; }
        public string service_id_claim { get; set; }
        public string service_id_serv_sheet { get; set; }
        public string delivery_type { get; set; }
        public Nullable<System.DateTime> date_waybill_set { get; set; }
    }
}
