//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipClaim.Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zipcl_counter_report
    {
        public int id_user { get; set; }
        public System.DateTime Дата_входа { get; set; }
        public string ФИО { get; set; }
        public string Login { get; set; }
        public string Контрагент { get; set; }
    }
}
